### ISSUE TITLE
Arguments of finalizePackageDescription have changed in Cabal 1.22.x

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/cabal2nix#115]
I'm on a system with 7.8.4. This results:
src/Cabal2Nix/Generate.hs:62:26:
    Couldn't match expected type ‘CompilerInfo’
                with actual type ‘CompilerId’
    In the fourth argument of ‘finalizePackageDescription’, namely
      ‘(CompilerId GHC (Version [7, 6, 3] []))’
    In the expression:
      finalizePackageDescription
        (configureCabalFlags pkg)
        (const True)
        (Platform I386 Linux)
        (CompilerId GHC (Version [7, 6, 3] []))
        []
        cabal
cabal: Error: some packages failed to install:
cabal2nix-1.72 failed during the building phase. The exception was:
ExitFailure 1

**Comment by peti** [comment]
The type `CompilerInfo` is a new addition in Cabal 1.22.x. You have to compile cabal2nix with Cabal < 1.22, i.e. by passing the command line flag `cabal configure --constraint "Cabal <1.22"`.

**Comment by peti** [comment]
The version compiles fine with Cabal 1.22.x: http://hydra.cryp.to/job/cabal2nix/master/cabal2nix.ghc7101.x86_64-linux.

**Comment by josiah14** [comment]
This build fails on Ubuntu 14.04.

Cabal 1.22.2.0
ghc 7.8.3

Same exact error message as before.

**Comment by peti** [comment]
Version 1.x of `cabal2nix` (i.e. the version available from Hackage) does not compile with Cabal 1.22.x. I edited the meta information on Hackage accordingly; `cabal install cabal2nix` should now succeed. Generally speaking, it's almost certainly better install this tool with `nix` since Nixpkgs has a much newer version than Hackage does. Running `nix-env -iA haskellngPackages.cabal2nix` should do the trick.
