### ISSUE TITLE
Adopt hackage2nix to use https://github.com/commercialhaskell/all-cabal-hashes/

### ISSUE THREAD

**Issue by shlevy** [NixOS/cabal2nix#118]
Right now, as far as I can tell hackage2nix is downloading the latest version of all of the packages in hackage. It would be nice if instead it read in the existing expression (which might be easier if instead hackage2nix generated json?) and only downloaded the new packages.

Also, it would be nice to have a way to update/add a specific package, regardless of the status of everything else in hackage.

**Comment by peti** [comment]
That's implemented already. Hashes are cashed in `~/.cache/cabal2nix`. Only new versions will be downloaded.

**Comment by shlevy** [comment]
That's not share between committers, though. It'd be good not to have to download all of hackage on every computer where I work on nixpkgs.

**Comment by peti** [comment]
Re single package updates: yes, that would be nice, but it's hard'ish to implement because then the tool would have to parse hackage-packages.nix and replace one entry in-place. It's doable, but I won't do it any time soon because I have other worries. :-)

**Comment by peti** [comment]
I just rsync'ed the cache directory to all my machines. The incremental downloads are not so large once you have a base cache to go from. Anyway, yes, it would be nice to have a smarter cache and/or to read those hashes from the hackage-packages.nix file. I just don't think it's a high priority right now, because I don't expect many people to re-generate that file at the moment. Also, note that you don't need all of hackage on your disk the entire time -- the garbage collector can throw these source tarballs away as it sees fit.

**Comment by shlevy** [comment]
BTW, do you think we can just ask hackage to make sha256 available?

**Comment by peti** [comment]
We can try. In a perfect world, the Cabal files distributed in the `00-packages.tar` tarball would contain those hashes in some `x-tarball-sha256:` field. Then we wouldn't have to download anything.

**Comment by shlevy** [comment]
Any idea who to reach out to about that?

**Comment by peti** [comment]
https://github.com/haskell/hackage-server/ or http://community.galois.com/mailman/listinfo/haskell-infrastructure might be the right place.

**Comment by peti** [comment]
Even better: adopt `hackage2nix` to take both the hashes and the cabal files from https://github.com/commercialhaskell/all-cabal-hashes/.
