### ISSUE TITLE
Separate packages for elisp

### ISSUE THREAD

**Issue by cocreature** [NixOS/cabal2nix#132]
There are a few packages that contain elisp, most notably hindent, structured-haskell-mode & ghc-mod. There are special cases for shm and ghc-mod to put the elisp in the right place but for hindent it ends up being in `share/x86_64-linux-ghc-7.8.4/hindent-4.1.1`. While it would be easy to add another special case for hindent, after a short discussion on irc I got convinced that splitting the packages and creating another package for the elisp stuff in emacs24Packages is the better solution. As I haven't used nix before, I'd like to know if you agree and if so what would be the best way to tackle this? Removing the elisp from the packages is obviously pretty simple but I'm not sure about the elisp packages. Ideally the would also be generate by hackage2nix so the two are always in sync, but they don't belong in haskellngPackages.

**Comment by peti** [comment]
Cc'ing @Fuuzetsu, who wants to do the same thing.

**Comment by Fuuzetsu** [comment]
I would imagine that we could preserve ELisp files in the original packages, just don't do anything with them. Then when we actually want the ELisp, we could depend on that and compile as separate package.

Just one idea of course. Not sure if this repository is the right place for this.

**Comment by cocreature** [comment]
@Fuuzetsu If the elisp files are preserved anyway, don't you think they should be put in $out/share/emacs/site-lisp so that it can be easily loaded instead of having them in some weird place where you need to search for?

**Comment by peti** [comment]
I don't believe that `cabal2nix` can auto-generate builds that magically do the right stuff with elisp files. At least I wouldn't how how to do this. As such, I think this issue is better discussed in the scope of Nixpkgs, i.e. https://github.com/NixOS/nixpkgs/issues/4561. If someone comes up with a way to automatic these matters in `cabal2nix`, then this issue should be re-opened, of course! Until then, I'm closing this.
