### ISSUE TITLE
Reduce hackage2nix memory requirements

### ISSUE THREAD

**Issue by shlevy** [NixOS/cabal2nix#160]
hackage2nix reliably OOMs my 2-gig box. It seems like it should be possible to run in constant space, no?

**Comment by peti** [comment]
I'm pretty sure that `hackage2nix` has O(1) space requirements; it's just that the constant factor is fairly large because the program performs some fairly sophisticated computations. Personally, I don't perceive the memory requirements as much of a problem. It's probably possible to reduce the requirements, but I probably won't put much effort into achieving that. For me, run-time performance is more important, really.

Having said that, you might be able to fix the issues you've run into simply by providing appropriate settings to the RTS, i.e. try compiling/running the binary with `-with-rtsopts=-M2G`. That should help?

**Comment by shlevy** [comment]
Tried that, now blocked by #161 . FWIW if this doesn't work out I think I'll just end up having to modify hackage-packages.nix directly.

**Comment by peti** [comment]
Can this issue be be closed?

**Comment by shlevy** [comment]
Testing again

**Comment by shlevy** [comment]
Cool, works with the above flag.
