### ISSUE TITLE
Can't find utf8-string v1, but can find v0.3.8

### ISSUE THREAD

**Issue by chexxor** [NixOS/cabal2nix#166]
I am trying to use cabal2nix to generate a Nix expression I can use to manage PureScript's dependencies while I develop on it.

Here's their cabal file - https://github.com/purescript/purescript/blob/master/purescript.cabal

I believe I used these commands in the cloned PureScript directory:

    $ cabal2nix --shell ./. > shell.nix
    $ cabal2nix ./. > project.nix

And added a default.nix file containing this:
    # default.nix
    { pkgs ? import <nixpkgs> {} }:
    pkgs.haskellngPackages.callPackage ./project.nix {}

When I tried to `nix-shell` or `nix-build` that, I got an error:

    Setup: At least the following dependencies are missing:
    utf8-string ==1.*

So, I added `jailbreak = true;` to the project.nix file, which fixed the build by finding and using utf8-string version 0.3.8 instead of version 1. Why can't it find version 1? Is it because it isn't formatted as 1.0.0?
The Hackage URLs shows for these indicate this possibility:

    http://hackage.haskell.org/package/utf8-string-1
    http://hackage.haskell.org/package/utf8-string-0.3.8

Thoughts?

**Comment by chexxor** [comment]
I chatted with Fuuzetsu in IRC about this issue. He believes it's not an issue with cabal2nix, as it doesn't try to do any version-matching. He says that an override should be placed in "common-configuration.nix" which changes the purescript package's `utf8-string` to `utf8-string_1`.

I was quite surprised to hear that cabal2nix doesn't do any version mappings, but whatever works, I guess.

Here's an idea: have a mapping in cabal2nix which maps `utf8-string: "1"` to the `utf8-string_1` package. And any other version of utf8-string would continue to do whatever is currently done.

**Comment by peti** [comment]
@chexxor, the easiest solution is to edit your generated `shell.nix` to expect `utf8-string_1` as an argument instead of the version-less `utf8-string` -- which is 0.3.8 by default. When 1.x came out, the vast majority of packages would not compile against the new version, so we had to stick to the old one by default. I'm not sure whether the situation has changed much recently, but I suppose it's a good time to try whether using version 1.x by default is sustainable solution at the time being.

Anyway, cabal2nix has nothing to do with this subject. Version resolution takes place in the Nixpkgs package set. In this particular case, the version choice is made in the `*.nix` files that you generated locally.

**Comment by chexxor** [comment]
Forgot to say - Thank you!
