### ISSUE TITLE
Expose hackage2nix as a library

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/cabal2nix#184]
Use case: overriding the default configuration to be able to generate a more fine-grained package sets with the cabal-provided versions on per-project basis.

**Comment by teh** [comment]
@Fuuzetsu would this allow to e.g. follow the stackage set of packages? Or to have a specific one for yesod?

**Comment by Fuuzetsu** [comment]
@teh with further work, yes, that's my motivation for this request

**Comment by nrolland** [comment]
that would be really good. having the benefits of nix immutability and the curated set of stockage would be really awesome.

**Comment by peti** [comment]
I agree that `hackage2nix` should be re-factored so that it's easier to re-use in external code. I believe that's a good idea mostly because it would help us clean up the code, which is fairly monolithic and messy at the moment.

I don't believe, however, that having `hackage2nix` available as a library is important for implementing support for Stackage. In fact, it's quite simple to track Stackage already: Download https://www.stackage.org/lts/cabal.config, edit the file slightly for syntax (or have a `sed` script do it automatically), add its contents to the [`defaultPackageOverrides`](https://github.com/NixOS/cabal2nix/blob/badda1eb05994906083085686dbdd86f13237e41/src/hackage2nix.hs#L301) list, and re-run `hackage2nix`. That would give you a Haskell package set based on Stackage.

Now, that approach isn't quite good enough for our purposes in Nixpkgs, because we would like to have Stackage support *in addition* to the bleeding-edge package set we currently provide. This means that the Stackage version list must go into [`extraPackages`](https://github.com/NixOS/cabal2nix/blob/badda1eb05994906083085686dbdd86f13237e41/src/hackage2nix.hs#L336) instead, to make sure `hackage2nix` provides all the package versions we need for Stackage even though some of those are older than the latest available version from Hackage. Finally -- and this is the only part that needs actual coding -- `hackage2nix` must be extended to generate a set of overrides, a `configuration-stackage.nix` file, if you will, that modifies our default choices (latest version) to the Stackage choice where appropriate.

I believe that this whole feature can be built into `hackage2nix` fairly easily; I see no need to have a separate tool for that purpose.

**Comment by bennofs** [comment]
That is one way to implement support for stackage. However, if we go that way, users can't easily generate their own package set, since then they would have to edit the global hackage-packages.nix. So, what about the following:

* stackage2nix is a tool that generates a file `stackage-packages.nix`, just like `hackage-packages.nix`
* we refactor `default.nix` in nixpkgs so that users are able to build their own package sets: stackage could then be implemented as just `stackagePackages = lib.makePackageSet ./stackage-packages.nix`.
* this makes it easy for users to build their own stackage-packages.nix from another stackage snapshot, or build a completely customized package set using their own tools

In fact, I've implemented a stackage2nix tool that does exactly this, and the code to make it use only ghc from hackagePackages is not much. If we want to go even further, we could build a "basePackages" that only contains the basic stuff provided by GHC and then build different package set upon that base set (like haskellPackages, stackagePackages, ...)

**Comment by nrolland** [comment]
whatever the tool used, it would seem logical to have as a result separated namespaces (haskellPackages, stackagePackages etc.. ) and not effectively mutate a global state.

I don't practically see why users would want to have there own sets, but, in theory, it seems an added benefit to have a consistent pattern to do that.

Following nixpkgs is always a surprise for what will break, so having stackage here would bring a much needed reliability and a much better story.

ps : I would love to and might take some time to understand @bennofs branch

**Comment by peti** [comment]
@bennofs,

> if we go that way, users can't easily generate their own package set, since then they would have to edit the global hackage-packages.nix.

I'm not sure I can follow. Would you mind giving an example of what a user might want to do that's not possible with `hackage-packages.nix` + `configuration-*.nix` overrides?

> stackage2nix is a tool that generates a file stackage-packages.nix, just like hackage-packages.nix

Won't those two files contain a lot of duplicate entries?

**Comment by bennofs** [comment]
> I'm not sure I can follow. Would you mind giving an example of what a user might want to do that's not possible with hackage-packages.nix + configuration-*.nix overrides? 

There are lots of different stackage snapshots, and I think we won't want to include packages for all different snapshots in hackage-packages.nix. As I understand stackage, most applications using stackage will depend on a very specific stackage snapshot (for example, nightly-08-07. Ok, some might also use LTS, but it's perfectly ok to pick some nightly snapshot and stick with it). If all packages have to be contained in hackage-packages.nix, then it's not easy to use a custom stackage snapshot, since you have to include the packages that are not in hackage-packages.nix too somehow. For example, nightly-08-07 might have vector-0.10, but perhaps the stackage snapshot that we include in nixpkgs has only vector-0.11. Then, if I want to use nightly-08-07, I can't just use a generated `configuration-*.nix`: I'll also have to figure out how to add the vector-0.10 package. I know that you can also add custom packages via overriding, but generating the needed custom entries will be a mess. 

> Won't those two files contain a lot of duplicate entries? 

Yes, the two files will neccessarily contain some duplicate entries. However, flag selection for example may be different (because of different dependencies). I'm not sure how often that'll actually happen in practice, but it just feels cleaner to me to avoid such problems fully. 

I'm not sure if it makes sense to include a recent stackage nightly snapshot in nixpkgs itself anyway, since nightly will be updated daily so it'll very often be out of date. We could at the LTS snapshots though, they don't change as often as far as I know.

**Comment by peti** [comment]
> As I understand stackage, most applications using stackage will depend on a very specific stackage snapshot (for example, nightly-08-07).
 
But how would a separate `stackage-packages.nix` set solve that problem? You can't put all versions of all packages into that file either, no?

**Comment by bennofs** [comment]
Yes, but users can generate their own stackage-packages.nix easily and use that to build the project.

**Comment by Fuuzetsu** [comment]
OK so my reply was aimed at the

>Or to have a specific one for yesod?

part; that's why I created the issue. I'd like to take a cabal file and spit out a package set with the versions matching there rather than the bleeding edge. This is needed when for example cabal freeze is used and you are expected to hack with the exact specified versions.

stackage stuff would be nice to have though not my initial motivation for this

**Comment by peti** [comment]
OK, I believe I've now understood @Fuuzets's and @bennofs's use cases. I'd suggest that we keep further Stackage architecture discussion out of ticket and create a new one for that purpose. Re-factoring `hackage2nix` for easier re-use is an important topic, and work towards that end is well underway. I'll keep you posted.

**Comment by peti** [comment]
Tasks remaining to close this issue:

 - [ ] Re-factor the code that generates and pretty-prints overrides into a separate module and re-use it in `cabal2nix` while generating `--shell` output.
 - [ ] Document `fromGenericPackageDescription` with some usage examples doctest style.
 - [ ] Document the new and improved `BuildInfo` type.
 - [ ] Re-add the `cabal2nix` function, implementing some kind of high-level interface to `fromGenericPackageDescription` that hides all this Hackage/Nixpkgs resolver business.
 - [ ] Move Nixpkgs resolver intelligence out of the `Distribution.Nixpkgs.Haskell.FromCabal` module.

**Comment by peti** [comment]
Massive re-factoring has takes place in 2c4ae6f869b3dd4d0026c729262ab0f0b9594d7b.

**Comment by peti** [comment]
Libraryfication of `hackage2nix` is complete, IMHO. The tool has shrunk to 200 lines of code. It's not super pretty yet, but I think it's quite readable. About the remaining tasks from https://github.com/NixOS/cabal2nix/issues/184#issuecomment-135162900:

- `cabal2nix --shell` can, in general, not produce the overrides that `hackage2nix` generates. `hackage2nix` requires a complete Hackage and Nixpkgs database to run. `cabal2nix` does not have that information available. Now, I suppose we could add support for those features to cabal2nix, but I'm reluctant to do that. The tool is overly complicated at the moment, and I'd rather clean it up than add new features at this point in time.

- I assumed that a simple `cabal2nix` function would be nice to have, but the truth is that I'm not sure about the interface of that function yet. At the moment, `fromGenericPackageDescription` takes *functions* that provide lookups into Hackage and Nixpkgs. I suspect things would be much easier if I'd take dictionaries instead. Anyway, my point is that this needs further thought before it can be solved, so I've decided to dub the current state good enough for now.

- Adding documentation is an ongoing process that's going to take a while. :disappointed:

**Comment by Fuuzetsu** [comment]
Awesome, thanks for your work, I'll open any issues as I encounter them.
