### ISSUE TITLE
.nix files generated by cabal2nix no longer pay attention to overrides in config.nix

### ISSUE THREAD

**Issue by stepcut** [NixOS/cabal2nix#186]
A couple months ago the output of `shell.nix` changed dramatically. One side effect is that it now uses `callPackage` like this:

     drv = pkgs.haskell.packages.${compiler}.callPackage f {};

however, that seems to ignore the overrides in my `config.nix` which are set like this:

    haskellPackages = superDuper.haskell.packages.override rec {

I can hackage around this by editting the `shell.nix` to use `haskellPackages` instead of `haskell.packages.${compiler}`.

    drv = pkgs.haskellPackages.callPackage f {};

However, I now want to add overrides for `ghcjs` and I have no idea how to make that work.

I've looked through the manual, but I can't figure out if I am doing something wrong or if there is a bug somewhere else in the system. I've tried do something like this in my `config.nix`:

        haskell.packages.ghcjs = superDuper.haskell.packages.ghcjs.override rec {

But that just results in:

    error: attribute ‘haskell.packages.ghc784.jailbreak-cabal’ missing, at "/Users/stepcut/nixpkgs/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix":45:21

Not sure where to go from here.

**Comment by peti** [comment]
You could define your local overrides for the compiler-specific package set, and then define

    haskellPackages = self.haskell.packages.ghc7101;

so that the overrides are applied in both `haskell.packages.ghc7101` and `haskellPackages`. http://hydra.nixos.org/build/23882731/download/1/nixpkgs/manual.html#how-to-override-package-versions-in-a-compiler-specific-package-set is probably a helpful resource for accomplishing that.

**Comment by peti** [comment]
The new cabal2nix versions remedies this issue. Thank you for the report!
