### ISSUE TITLE
Create a way to mark packages broken on certain platforms 

### ISSUE THREAD

**Issue by peti** [NixOS/cabal2nix#194]
This is necessary to fix Darwin build errors for the release branch (https://github.com/NixOS/nixpkgs/issues/9471).

**Comment by Mathnerd314** [comment]
What about setting hydraPlatforms? e.g. as in
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/uhc/default.nix#L52
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libjpeg-turbo/default.nix#L21

**Comment by edolstra** [comment]
@Mathnerd314 `hydraPlatforms` should only be used for packages that *do* work on certain platforms, but that we don't want to build for other reasons (e.g. because they're too large). For packages that just don't work, you should use `platforms`.

(It's not just Darwin BTW, there are a few dozen packages that only fail on i686-linux: http://hydra.nixos.org/eval/1219294#tabs-still-fail)
