### ISSUE TITLE
Support Stackage

### ISSUE THREAD

**Issue by peti** [NixOS/cabal2nix#205]
We would like to provide meaningful support for [Stackage](http://www.stackage.org) in [Nixpkgs](http://www.nixos.org/nixpkgs). It's not even that difficult to do, really, but the question is how to do it in a way that's most beneficial to both users of Nix and Stackage. Ideally, we would achieve the following goals:

1. Nix users have package sets that correspond to various versions of [LTS Haskell](http://www.stackage.org/lts) as well as [Stackage nightly](http://www.stackage.org/nightly).

2. Builds results, log files, etc. from our continuous integration infrastructure should be reported back to Stackage to help them detect and fix issues that might exist.

Open questions:

 - How do deal with release branches such as [release-15.09](https://github.com/NixOS/nixpkgs/tree/release-15.09)? Updating the LTS package sets in these branches seems reasonable, because breakage caused by these updates is considered in issue in Stackage, too, and should be detected (and fixed). On the other hand, these updates may affect packages outside of Stackage, which would be our problem then.

 - What happens to the bleeding edge `haskellPackages` set that we currently have? Do we still maintain that? Some of our packages in that set are more recent than Stackage Nightly, which is nice. At the same time, having our own "nightly" package set in addition to the one Stackage provides feels like an unnecessary duplication of effort.

- What happens to our package sets that target older compilers, like `haskell.packages.ghc784`? Do we change those to track the appropriate (i.e. the latest available) LTS release for that compiler?

**Comment by grwlf** [comment]
I realized that both Haskell teams I work with   have moved to Stack recently (they use mainly Ubuntu). That is why I need Stack tools in order to stay in sync with them while developing.

> What happens to the bleeding edge haskellPackages set that we currently have? Do
> we still maintain that? Some of our packages in that set are more recent than 
> Stackage Nightly, which is nice. At the same time, having our own "nightly" package 
> set in addition to the one Stackage provides feels like an unnecessary duplication of 
> effort.

I personally use haskellPackages only to install cabalInstall (Here is the config for reference https://github.com/grwlf/nixcfg/blob/master/src/include/haskell.nix). It seems that full haskellPackages is not important for me, by the minimal set is still required to be able to install _very_ fresh packages from the HackageDB into local ~/.cabal/ database. If we are speaking about complete replacement of haskellPackages, then I'd like to be sure that this use-case is still supported.

**Comment by peti** [comment]
@grwlf, you realize, though, that you *can* develop with Stack just fine on NixOS today, right? I'm developing `cabal2nix` with Stack.

**Comment by grwlf** [comment]
Err, not quite :) AFAIK, Stack deploys pre-build ghc binaries, how does Nix handle that?

**Comment by peti** [comment]
@grwlf, `stack` quite happily uses the ghc binary provided by Nix (as long as it's the right version). As I've said, I *am* developing the very package who's bug tracker we're using right now with `stack` on NixOS.

**Comment by Mathnerd314** [comment]
My thoughts on the open questions:
* Upgrading is not an atomic action; it consists of adding the new version and dropping the old version. So for release branches, just ensure that you don't drop old Stackage versions.
* Stackage already does a build/test cycle before uploading snapshots (there's mention of a Jenkins machine [here](https://github.com/fpco/stackage#build-the-package-set)). So if Hydra fails to build some part of Stackage then it's probably something broken in NixOS.
* haskellPackages, unlike Stackage nightlies, auto-jailbreaks version bounds. I assume this allows a significant collection of packages to compile; we should tell Stackage (or maybe just Hackage?) about the jailbroken packages so that they can update the version bounds. But there's no duplication of effort involved since Stackage doesn't jailbreak. So we should have both the nightlies and haskellPackages.
* Using an old compiler with an old LTS release makes some sense, but I imagine there are people who want recent package versions with an old GHC. So again I think we should just have both.

**Comment by peti** [comment]
Implemented in 2aaa587b71e19ff105fc482414f9dbc3060d57b6. `haskell.packages.lts-x_y` is a family of package sets that correspond to LTS version x.y. We support *all* LTS releases since version 0.0, but only 3.x is tested. Earlier versions may have an occasional build failure. The default `haskellPackages` set tracks Stackage Nightly. Further details will be added to the Nixpkgs manual ASAP.

**Comment by jb55** [comment]
Does this mean nixpkgs no longer tracks Hackage?

**Comment by peti** [comment]
No, we track Hackage. But for packages that are in Stackage, we prefer those versions that Stackage mandates. For everything else, we use the latest available version.

**Comment by jb55** [comment]
as in, is there still a way to restore the previous behavior of haskellPackages. I can't see how from these commits.

**Comment by peti** [comment]
No, there is no way to restore the previous behavior ("latest version of everything").

**Comment by jb55** [comment]
This seems very unfriendly for Haskell development then. I have some packages using bleeding edge versions not in stackage (such as vector 0.11), so I have no way of continuing development of those libs if I use nix? I guess it should still be possible to do that if I run hackage2nix myself somehow?

**Comment by peti** [comment]
`vector-0.11.0.0` is available in `haskellPackages`. The latest versions are still there; they just aren't used by default. You can override the default version in your package set, if you want (or rather: create a new package set that has those default versions that you want).

**Comment by jb55** [comment]
ah ok that makes sense now. thanks!

**Comment by Mathnerd314** [comment]
@peti Perhaps hackage2nix could generate a ``latest.nix`` package set with those overrides and jailbreaks? It wouldn't have too many users, but ``lts-0.0`` won't have many either.

**Comment by nrolland** [comment]
That is really practical in terms of development workflow. Latest everything was not a sensible default.
Thank you !

**Comment by grwlf** [comment]
Thanks, great!

2015-09-20 12:28 GMT+03:00 Nicolas Rolland <notifications@github.com>:

**Comment by charles-cooper** [comment]
Question: @peti Are there any plans to continuously build the LTS releases on hydra? Say the most recent N releases.

**Comment by nrolland** [comment]
i just installed ghc from 5.5 with a bunch of packets, and I am not sure which are cached or not. I would gladly contribute some $ for a mac cloud hydra, as my weak Mac mini is getting swamped

**Comment by peti** [comment]
@charles-cooper, in the light of https://github.com/NixOS/nixpkgs/issues/12203 I believe it's unlikely that `hydra.nixos.org` will pick up any LTS package sets other than Stackage Nightly, which is all it's building right now. The situation *might* improve soon because of radical changes in Hydra's internal architecture that will increase performance a lot, but we can only speculate how soon those changes will materialize (if ever).
