### ISSUE TITLE
Feature: generate full dependency graph

### ISSUE THREAD

**Issue by spinus** [NixOS/cabal2nix#246]
The feature to generate derivation descriptions for all dependencies of the package would be very nice. Similarly to pypi2nix or npm2nix/node2nix tools. 

nixpkgs are moving and sometimes break my apps so I need to write all those manually.

**Comment by peti** [comment]
We cannot do that for Haskell packages because for any non-trivial package there's a space of thousands of possible version combinations to choose one, and `cabal2nix` cannot make that choice. We could make *some choice*, I suppose, by re-implementing large parts of `cabal-install`, but even then the result would necessarily be helpful for our users.

What you probably want is the `callHackage "foo" "1.0" {}` function from Nixpkgs, which gives you access to all of Hackage.

**Comment by spinus** [comment]
hmm, pypi2nix can do that, npm2nix/node2nix can do that, I think shouldn't be hard problem for cabal2nix. 

Constraints are usually provided by the user (requriements.txt in pypi2nix, package.json in npm2nix) and resolver tries to find correct matches. Yes, I think part of cabal (resolver) could be used for that.

I think in haskell world this decision can be done with higher confidence level than in python or javascript world (and this tactics works most of the time in those worlds also). So you upgrade your package set, compile:
- breaks, fix constraints and compile again
- works - perfect

(in python or javascript instead of relaying only on compilation I also relay on my test suite results)

**Comment by peti** [comment]
Well, a PR that implements this behavior would be gladly accepted.

**Comment by spinus** [comment]
I'm just doing first steps in haskell so I'm not sure I'll be able to implement anything useful soon, hence I opened this ticket :)
