### ISSUE TITLE
How to update hackage2nix?

### ISSUE THREAD

**Issue by hamishmack** [NixOS/cabal2nix#267]
@peti what needs to be updated to make these https://github.com/hamishmack/nixpkgs/commit/23ce8d06dce68cfc67956d06948481193134a2a7 changes to hackage-packages.nix?

**Comment by hamishmack** [comment]
Here are some things I would like to try https://github.com/hamishmack/cabal2nix/commit/4878dcca853c6cb8ed55034c4f05f46b31853123.  How do I run this?  `update-nixpkgs.sh` seems to need a `hackage` git repo.  Where can I get that?

**Comment by mdorman** [comment]
@hamishmack So you can clone the hackage repo from https://github.com/commercialhaskell/all-cabal-hashes

**Comment by mdorman** [comment]
@hamishmack Regarding your specific changes, I've left some comments in the change you linked to; I would just like to emphasize that my goal in giving feedback is to try and arrive at the most minimal and most robust set of override bits that are necessary---because my experience a month or two ago when I cleaned a bunch of stuff up was that it's easy for stuff to end up invalidated by changes in both the greater hackage and nix environments, and since most of these package don't get auto-built, it doesn't get noticed until it hits an end-user.

That said, if it's necessary, it's necessary; I hope my comments are clear and helpful in determining what is or isn't.

I'm happy to work with you on this, though I am having some outpatient surgery done tomorrow that means I will probably be unavailable or available but drugged enough to perhaps be the opposite of useful. :)

**Comment by peti** [comment]
I trust this issue has been solved. Please let me know if I assume wrong!
