### ISSUE TITLE
qtah-qt5 gets nonexistent `qtah` dependency

### ISSUE THREAD

**Issue by yorickvP** [NixOS/cabal2nix#347]
qtah specifies `extra-libraries: qtah`, and this causes the following:
```
$ cabal2nix cabal://qtah-qt5
{ mkDerivation, base, binary, bytestring, Cabal, directory
, filepath, hoppy-runtime, HUnit, qtah, qtah-cpp-qt5
, qtah-generator, qtbase, stdenv
}:
mkDerivation {
  pname = "qtah-qt5";
  version = "0.4.0";
  sha256 = "c3d09be633a85cffb8847c313c6a3a1bec19bb6b7374d5f536bd37ea57e640ac";
  setupHaskellDepends = [ base Cabal directory filepath ];
  libraryHaskellDepends = [
    base binary bytestring hoppy-runtime qtah-cpp-qt5 qtah-generator
  ];
  librarySystemDepends = [ qtah ];
  libraryToolDepends = [ qtbase ];
  testHaskellDepends = [ base hoppy-runtime HUnit ];
  testSystemDepends = [ qtah ];
  homepage = "http://khumba.net/projects/qtah";
  description = "Qt bindings for Haskell";
  license = stdenv.lib.licenses.lgpl3;
}
```
Of course, qtah doesn't exist and this fails to evaluate. Something is wrong, somewhere, but I don't know whose bug this is. How do I fix it?

**Comment by peti** [comment]
There is nothing wrong here. The Cabal file declares a dependency on the library library `qtah`, and so you must pass an argument to this function that provides that library for the build to succeed. Personally, I don't know what `qtah` is and it seems like it's not packaged in Nixpkgs, but I don't know for sure.

At any rate, this does not look like a bug at all.

**Comment by yorickvP** [comment]
`libqtah.so` is provided by the `qtah-cpp` haskell package. Maybe it should be renamed `libqtah-cpp.so`?

**Comment by peti** [comment]
`qtah-qt5` lists the dependency as:

    extra-libraries: qtah

That refers to a system library.  It's theoretically possible that a Haskell package provides that library, but it's very unlikely. If it did, then that package should be listed as a *Haskell dependency* to ensure that it's available during build-time, and I don't see any such dependency in `qtah-qt5`. Besides, a Haskell package called `qtah-cpp` does not exist on Hackage.

**Comment by yorickvP** [comment]
The package is https://hackage.haskell.org/package/qtah-cpp-qt5 (but the source builds to both -qt4 and -qt5, that's the reason for the confusion). The Haskell package uses qmake to build c++ files and make that library.

**Comment by peti** [comment]
Well, I honestly don't what what `qtah` is and how it works. All I can say is that the Nix expression `cabal2nix` generates is perfectly okay and a correct mapping of the information specified in the Cabal file. The intricacies of getting all those packages built with Nix are beyond me, I'm afraid. The thing know -- the cabal2nix generator -- does what it is supposed to do.

**Comment by khumba** [comment]
For what it's worth, I've changed the build system now, which might help with this.  The `qtah-cpp` package has a private `libqtah.so`, and that's what the `qtah` package's `extra-libraries` line is referring to, however, the latter's `Setup.hs` is what injects the `extraLibDir` to be able to find it (it gets this from `qtah-cpp`), so looking at `qtah.cabal` isn't enough.

With the latest release 0.5.0, I [removed](https://gitlab.com/khumba/qtah/commit/f88b53132cc4c4e13e31707d7a58ed1f6819c069) the `extra-libraries` line from the `qtah.cabal`, and `Setup.hs` adds that library dependency at the same time it adds the directory it's in to the search path, so that there's never a dependency without a way to find it.  It was [reported](https://gitlab.com/khumba/qtah/merge_requests/13) that this fixed an issue with cabal2nix, which sounds like the issue here.
