### ISSUE TITLE
cabal2nix can fail if the `hpack` version is newer

### ISSUE THREAD

**Issue by parsonsmatt** [NixOS/cabal2nix#507]
I'm testing a build out and depending on a repository. I invoked `cabal2nix` like so:

```
cabal2nix https://github.com/parsonsmatt/persistent-discover --revision 327106b1a74d68def6f765e4df435d3f567163bc > .nix/deps/persistent-discover.nix
```

The output when trying to enter `nix-shell` is this:

```
$ nix-shell
warning: dumping very large path (> 256 MiB); this may run out of memory
these derivations will be built:
  /nix/store/j5ym74w47qa1q7j6fs47dfn77bqrgly1-persistent-discover-0.1.0.3.drv
  /nix/store/fw8ps5sal8f6mwgim7389fb6qv4nwa0q-hoogle-local-0.1.drv
  /nix/store/klij767lxkll2w91hg6i1a2sw4q12n6g-ghc-8.10.3-with-packages.drv
building '/nix/store/j5ym74w47qa1q7j6fs47dfn77bqrgly1-persistent-discover-0.1.0.3.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/bsr0vynkkbz2rmhzf6x64yahigyydj7c-ghc-8.10.3.
unpacking sources
unpacking source archive /nix/store/wfy2cwydn33ql1za6f30a08282s8ma5p-persistent-discover-327106b
source root is persistent-discover-327106b
patching sources
persistent-discover.cabal was generated with a newer version of hpack, please upgrade and try again.
builder for '/nix/store/j5ym74w47qa1q7j6fs47dfn77bqrgly1-persistent-discover-0.1.0.3.drv' failed with exit code 1
cannot build derivation '/nix/store/klij767lxkll2w91hg6i1a2sw4q12n6g-ghc-8.10.3-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/klij767lxkll2w91hg6i1a2sw4q12n6g-ghc-8.10.3-with-packages.drv' failed
```

The error line is this:

> `persistent-discover.cabal was generated with a newer version of hpack, please upgrade and try again.`

I've worked around this by adding `--force` to our `hpack` invocation at work, so `hpack --force .` will allow it to override a thing. `cabal2nix` should probably do this too, in the event that a Git repo has a newer `hpack` than the one built in to the environment.

**Comment by parsonsmatt** [comment]
Seems like modifying `prePatch` in the generated expression works:

```diff
-  prePatch = "hpack";
+  prePatch = "hpack --force";
```

Not sure if this is something you want to build in to the library, but it seems like a reasonable default.

**Comment by cdepillabout** [comment]
I was able to reproduce this locally.

In this instance, it looks like `persistent-discover` has both a `.cabal` file and a `package.yaml` file:

https://github.com/parsonsmatt/persistent-discover/tree/327106b1a74d68def6f765e4df435d3f567163bc

It seems like a better fix would be to force `cabal2nix` to use the `.cabal` file even if a `package.yaml` file exists as well.

Michael Snoyman recently suggested that people should always check in a `.cabal` file even if they are using a `package.yaml` file: https://www.fpcomplete.com/blog/storing-generated-cabal-files/.  So I think it makes sense for us to use the `.cabal` file instead of `package.yaml`, if the `.cabal` file exists.

------------------------------

In the case where there is no `.cabal` file, would it be slightly dangerous to generate the `.cabal` file with old version of `hpack`?  I guess there could be some weird non-backwards compatible change in `hpack` that causes libraries to compile correctly, but silently misbehave.

Although it seems like this would be just an small edge case, and most users would want to use `hpack --force`.

I am in favor of merging in #508.

------------------------------

@parsonsmatt If you're looking for a work-around, in this case you could use `cabal2nix --no-hpack`.

**Comment by parsonsmatt** [comment]
> In the case where there is no .cabal file, would it be slightly dangerous to generate the .cabal file with old version of hpack? I guess there could be some weird non-backwards compatible change in hpack that causes libraries to compile correctly, but silently misbehave.

I don't think you'd get an error message at all in that case. `hpack` is checking the existing `.cabal` file, and *if* it was generated with a newer version if `hpack`, it fails to overwrite it. If there's no `.cabal` file, then `hpack` does whatever it can with the `package.yaml`. There's a chance that a feature of `package.yaml` is unsupported in the version of `hpack` used, but this would fail no matter what we do (and there's no way to check it, anyway).
