### ISSUE TITLE
Hoogle Data Fails

### ISSUE THREAD

**Issue by tdimiduk** [NixOS/cabal2nix#52]
With a default install of Ceh, hoogle appears to be broken. It will install fine, but then it needs to fetch data and cannot because the store is read only:

```
$ hoogle data
hoogle: /nix/store/w6lwbndblqn4ax3gl6agqm0l0slwkfgi-haskell-hoogle-ghc7.6.3-4.2.19-profiling/share/hoogle-4.2.19/databases: createDirectory: permission denied (Permission denied)
```

I am on Ubuntu 12.04 if that is important, and am happy to provide any other information that is useful. 

```
$ uname -a
Linux owl 3.5.0-32-generic #53-Ubuntu SMP Wed May 29 20:23:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by berdario** [comment]
Since this is the 3rd/4th result when googling "nixos hoogle", For other people that might stumble upon this:

What you probably want is the [hoogle-local](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/haskell/hoogle/local.nix) package, that comes installed with a local hoogle database already available
